import Footer from "@/components/Footer/Footer"
import Navbar from "@/components/Navbar/Navbar"
import Head from "next/head"

interface MainProps {
    children?: React.ReactNode
}

export default function Main({ children }: MainProps) {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.jpeg" />
                <title>Portal Lacrei</title>
            </Head>
            <Navbar/>
            {children}
            <Footer>
                
            </Footer>
        </>
    )
}
