name: NextJS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ">=17.3.1"
      uses: actions/setup-node@v1
      with:
        node-version: ">=17.3.1"

    - name: Build
      run: |
        npm install -g yarn
        yarn install --frozen-lockfile
        yarn build
